spring.application.name=azurewebapp
#server.port=8081

server.port=8081
server.ssl.key-store=/home/ec2-user/keystore.p12
server.ssl.key-store-password=pass123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=myapp


